services:
  web:
    container_name: marswide_frontend
    image: marswide_frontend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "start"]
    restart: always